name: cached_network_image_web_ce
description: Web implementation of CachedNetworkImage (Community Edition)
version: 2.1.1
homepage: https://github.com/Erengun/flutter_cached_network_image_ce
repository: https://github.com/Erengun/flutter_cached_network_image_ce/tree/develop/cached_network_image_web
publish_to: none

topics:
  - cache
  - image
  - network-image

environment:
  sdk: ^3.11.0
  flutter: '>=3.41.0'

dependencies:
  cached_network_image_platform_interface_ce:
    git: https://github.com/kumsumit/cached_network_image_platform_interface_ce.git
  flutter:
    sdk: flutter
  web: ^1.1.1

dev_dependencies:
  file: '>=7.0.0 <8.0.0'
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
